image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://localhost:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  image: registry.crudus.no/crudus-devices/platformio:latest
  script:
    - platformio run
    - upload .pioenvs/featheresp32/firmware.bin $CI_PROJECT_PATH/featheresp32 firmware.bin
  only:
    - master

build_tag:
  stage: build
  image: registry.crudus.no/crudus-devices/platformio:latest
  script:
    - platformio run
    - |
      if [ ! -z "$device_id" ]; then
      upload .pioenvs/featheresp32/firmware.bin $CI_PROJECT_NAME/$platform/$device_id $CI_COMMIT_TAG.bin
      exit 0
      fi
  only:
    - tags
    # - $SOME_VARIABLE